[application]

#------------------------------------------
# Web
#------------------------------------------
[web.app]
title = "Theo Manager"
[web.resource]
style = []
script = []
[web.resource.dev]
script = []
[web.watcher]
index_on_404 = true
watch_path = ["src", "assets"]
[web.wasm_opt]
level = "z"
debug = false
#------------------------------------------
# Bundler
#------------------------------------------
[bundle]
identifier = "io.github.theomanager"
publisher = "MarckFp"
icon = [
    "icons/32x32.png",
    "icons/64x64.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
    "icons/icon.png",
    "icons/Square107x107Logo.png",
    "icons/Square142x142Logo.png",
    "icons/Square150x150Logo.png",
    "icons/Square284x284Logo.png",
    "icons/Square30x30Logo.png",
    "icons/Square310x310Logo.png",
    "icons/Square44x44Logo.png",
    "icons/Square71x71Logo.png",
    "icons/Square89x89Logo.png",
    "icons/StoreLogo.png"
]
copyright = "Copyright 2025 TheoManager"
category = "Utility"
short_description = "An application to manage you congregation"
long_description = """
An amazing application that let you manage, handle and configure everything related to your congregation in an easy, fast and secure way.
"""
#------------------------------------------
# Windows
#------------------------------------------
[bundle.windows]
icon_path = "icons/icon.ico"
allow_downgrades = false
tsp = false
webview_install_mode = {DownloadBootstrapper = {silent = true}}
silent = true
[bundle.windows.nsis]
installer_icon = "icons/icon.ico"
install_mode = "Both"
display_language_selector = false

#------------------------------------------
# MacOS
#------------------------------------------
[bundle.macos]
hardened_runtime = true
[bundle.macos.files]
